post:
  x-version: [V1.3, 2020.05.21]
  x-role: [电商平台, 服务商, 直连商户]
  tags:
    - 基础支付∙合单支付
  summary: 合单下单-APP支付API
  description: 使用合单支付接口，用户只输入一次密码，即可完成多个订单的支付。目前最多一次可支持50笔订单进行合单支付。 [官方文档](https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/combine/chapter3_1.shtml)
  parameters:
    - name: _
      in: body
      required: true
      schema:
        $ref: '../../definitions/Transaction.yaml#CombinationBase'
  responses:
    200:
      schema:
        type: object
        required:
          - prepay_id
        properties:
          prepay_id:
            type: string
            description: 预支付交易会话标识
            example: wx201410272009395522657a690389285100
